name: app

type: php:8.2

relationships:
    database:
        service: mysql
        endpoint: mysql

dependencies:
    php:
        composer/composer: "^2"

runtime:
    extensions:
        - apcu
        - blackfire
        - ctype
        - iconv
        - mbstring
        - sodium
        - xsl
        


    php:
        opcache.preload: config/preload.php
build:
    flavor: none

disk: 1024

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

mounts:
    "/var": { source: local, source_path: var }
    


hooks:
    build: |
        set -x -e

        echo $FOO
        echo $FOO_VAR
        echo "Building .env file"
        echo $APP_ENV
        echo "APP_ENV=${APP_ENV}" > .env
        echo "APP_ENV={$APP_ENV}" > .env
        echo "APP_SECRET=$(platform environment:variable:get env:APP_SECRET --pipe)" >> .env
        echo "CORS_ALLOW_ORIGIN=$(platform environment:variable:get env:CORS_ALLOW_ORIGIN --pipe)" >> .env
        echo "JWT_PASSPHRASE=$(platform environment:variable:get env:JWT_PASSPHRASE --pipe)" >> .env
        echo "JWT_PUBLIC_KEY=$(platform environment:variable:get env:JWT_PUBLIC_KEY --pipe)" >> .env
        echo "JWT_SECRET_KEY=$(platform environment:variable:get env:JWT_SECRET_KEY --pipe)" >> .env
        echo "DATABASE_URL=$(platform environment:variable:get env:DATABASE_URL --pipe)" >> .env
        echo "Completed building .env file"
        curl -fs https://get.symfony.com/cloud/configurator | bash
        NODE_VERSION=18 symfony-build
        echo  .env
        




crons:
    security-check:
        # Check that no security issues have been found for PHP packages deployed in production
        # See https://github.com/fabpot/local-php-security-checker
        spec: '50 23 * * *'
        cmd: if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ]; then croncape php-security-checker; fi


